const express = require("express");
const app = express();
app.use(express.json());
const userControllers = require("./controllers/userControllers");
const movieControllers = require("./controllers/movieControllers");
app.get("/api/users", userControllers.getUsers);
app.get("/api/users/:id", userControllers.getUsersByID);
app.get("/api/movies", movieControllers.getMovies);
app.get("/api/movies/:id", movieControllers.getMovieById);
app.post("/api/movies", movieControllers.postMovie);
app.post("/api/users", userControllers.postUsers);
module.exports = app;